title: Guillaume

email: clochard.guillaume@gmail.com
description: Guillaume's personal website and blog
twitter_username: guillaumewuip
github_username: guillaumewuip

baseurl: ""
url: "https://guillaume.wuips.com"

markdown: kramdown
remote_theme: riggraz/no-style-please
plugins:
  - jekyll-feed

favicon: "favicon.png"

theme_config:
  back_home_text: ".."
  date_format: "%d/%m/%Y"

collections:
  projects:
    output: true
    permalink: /projects/:year-:month-:day-:title
  talks:
    output: true
    permalink: /tech/talks/:year-:month-:day-:title
  posts:
    output: true
    permalink: /tech/posts/:year-:month-:day-:title
  mentalModels:
    output: true
    permalink: /tech/mental-models/:title

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: post
  - scope:
      path: ""
      type: mentalModels 
    values:
      layout: mentalModel
