title: Guillaume
email: clochard.guillaume@gmail.com
description: Guillaume Wuip personnal website
baseurl: ""
url: "https://guillaume.wuips.com"
twitter_username: guillaumewuip
github_username: guillaumewuip

# Build settings
markdown: kramdown

collections:
  projects:
    output: true
    permalink: /projects/:title

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: post
