title: Guillaume

email: clochard.guillaume@gmail.com
description: Personnal website and blog
twitter_username: guillaumewuip
github_username: guillaumewuip

baseurl: ""
url: "https://guillaume.wuips.com"

markdown: kramdown
remote_theme: riggraz/no-style-please
plugins:
  - jekyll-feed

favicon: "favicon.png"

collections:
  projects:
    output: true
    permalink: /projects/:title
  talks:
    output: true
    permalink: /talks/:title
  posts:
    output: true
    permalink: /posts/:title

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: post
