title: Guillaume
email: guillaume@wuips.com
description: Guillaume Wuip personnal website
baseurl: ""
#url: "http://guillaume.wuips.com"
url: "http://localhost:4000"
twitter_username: guillaumewuip
github_username: guillaumewuip

# Build settings
markdown: kramdown

collections:
  projects:
    output: true
    permalink: /projects/:title

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: post
